# Generated by Django 2.2.16 on 2022-05-16 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220516_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviews.Titles', verbose_name='reviews'),
        ),
    ]
